# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.4.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm install apify-cli -g
          - apify login --token $APIFY_TOKEN
    branches:
        master:
          - step:
              script:
                - apify push --build-tag latest
        develop:
          - step:
              script:
                - apify push --build-tag beta

